openapi: 3.1.0
info:
  version: 1.0.0
  title: ML Experiment Visualizer API
  contact:
    name: Contact the "; drop table users" team
    email: dyufyodorov@edu.hse.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: "Find out the MLDev docs."
  url: 'https://gitlab.com/mlrep/mldev/-/wikis/new-format-of-experiment.yml-configuration#step5'
components:
  responses:
    ClientError:
      description: client error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ErrorDto'
    ServerError:
      description: server error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ErrorDto'
  schemas:
    ErrorDto:
      type: object
      description: error description
      properties:
        title:
          type: string
          description: error title
          example: NullPointerException
        description:
          type: string
          description: error description
      required:
        - title
        - description
    WebEditorChangeEventDto:
      type: object
      description: A symbol change event
      properties:
        lineIndex:
          type: integer
        posIndex:
          type: integer
        symbolVal:
          type: string
    BusChangeEventDto:
      type: object
      description: A file content change event
      properties:
        fileURL:
          type: string
        fileContentVal:
          type: string
    CredentialsEventsDto:
      type: object
      description: A credentials change event
      properties:
        username:
          type: string
        password:
          type: string
        fileURLPreffix:
          type: string
paths:
  /publish:
    post:
      summary: Publish an event into the bus
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/BusChangeEventDto'
                - $ref: '#/components/schemas/WebEditorChangeEventDto'
      responses:
        '200':
          description: successful operation
        '500':
          description: internal error
  /subscribe:
    post:
      summary: Gets the current expirement's visualization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentDto'
      responses:
        '200':
          description: successful operation
        '500':
          description: internal error
