apiVersion: apps/v1
kind: Deployment
metadata:
  name: drop-table-users-deployment
  namespace: droptableusers-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-editor-for-experiments
  template:
    metadata:
      labels:
        app: web-editor-for-experiments
    spec:
      containers:
        - name: we-lib-app
          image: iluhander/we-lib-app:latest
          ports:
          - containerPort: 3000
        - name: we-main-app
            image: iluhander/we-main-app:latest
            ports:
            - containerPort: 3002
        - name: we-web-editor
            image: iluhander/we-web-editor:latest
            ports:
            - containerPort: 3005
        - name: we-visualizer
            image: iluhander/we-visualizer:latest
            ports:
            - containerPort: 3006
